CREATE PROCEDURE usp_NEW_USER
@CUSTOMER_NUM DECIMAL(2),
@LAST_NAME CHAR(15),
@FIRST_NAME CHAR(15),
@ADDRESS CHAR(25),
@CITY CHAR(25),
@STATE CHAR(2),
@POSTAL_CODE CHAR(5),
@PHONE_NUM CHAR(12),
@GAMERTAG CHAR(15),
@MEMBERSHIP CHAR(6), 
@EXPIRATION_DATE DATE
AS
BEGIN
INSERT INTO XBOXLIVE(CUSTOMER_NUM, LAST_NAME, FIRST_NAME, ADDRESS, CITY, STATE, POSTAL_CODE, PHONE_NUM, GAMERTAG, MEMBERSHIP, EXPIRATION_DATE)
VALUES (@CUSTOMER_NUM, @LAST_NAME, @FIRST_NAME, @ADDRESS, @CITY, @STATE, @POSTAL_CODE, @PHONE_NUM, @GAMERTAG, @MEMBERSHIP, @EXPIRATION_DATE)

INSERT INTO OFFICE365(CUSTOMER_NUM, LAST_NAME, FIRST_NAME, ADDRESS, CITY, STATE, POSTAL_CODE, PHONE_NUM, MEMBERSHIP, EXPIRATION_DATE)
VALUES (@CUSTOMER_NUM, @LAST_NAME, @FIRST_NAME, @ADDRESS, @CITY, @STATE, @POSTAL_CODE, @PHONE_NUM, @MEMBERSHIP, @EXPIRATION_DATE)

INSERT INTO GROOVEMUSIC(CUSTOMER_NUM, LAST_NAME, FIRST_NAME, ADDRESS, CITY, STATE, POSTAL_CODE, PHONE_NUM, MEMBERSHIP, EXPIRATION_DATE)
VALUES (@CUSTOMER_NUM, @LAST_NAME, @FIRST_NAME, @ADDRESS, @CITY, @STATE, @POSTAL_CODE, @PHONE_NUM, @MEMBERSHIP, @EXPIRATION_DATE)
END;