CREATE PROCEDURE usp_EXPIRE_MEMBERSHIP
@MEMBERSHIP CHAR(8)
AS
UPDATE XBOXLIVE
SET MEMBERSHIP = 'SILVER'
WHERE EXPIRATION_DATE = GETDATE()

UPDATE OFFICE365
SET MEMBERSHIP = 'N/A'
WHERE EXPIRATION_DATE = GETDATE()

UPDATE GROOVEMUSIC
SET MEMBERSHIP = 'N/A'
WHERE EXPIRATION_DATE = GETDATE()