CREATE PROCEDURE usp_DEL_EXPIRATION
@EXPIRATION_DATE DATE
AS
DELETE 
FROM XBOXLIVE
WHERE EXPIRATION_DATE = @EXPIRATION_DATE

DELETE 
FROM OFFICE365
WHERE EXPIRATION_DATE = @EXPIRATION_DATE

DELETE
FROM GROOVEMUSIC
WHERE EXPIRATION_DATE = @EXPIRATION_DATE

